server:
  port: 8083
  servlet:
    context-path: /api/v1
spring:
  application:
    name: insite-read-service
  config:
    import: optional:file:.env[.properties]

influxdb:
  url: ${INFLUX_HOST}
  token: ${INFLUX_TOKEN}
  org: ${INFLUX_ORG}
  bucket: ${INFLUX_BUCKET}

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    server-url:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    com.thirty.insitereadservice.client: DEBUG