server:
  port: 8082 #0
  servlet:
    context-path: /api/v1

spring:
  application:
    name: insite-write-service
  config:
    import: optional:file:.env[.properties]

influxdb:
  url: http://localhost:8086
  token: behappy1234
  org: thirty
  bucket: insite

#eureka:
#  instance:
#    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    server-url:
#      defaultZone: http://localhost:8761/eureka

