version: '3'
services:
  mysql:
    image: mysql:8.0.21
    ports:
      - "3308:3306"
    environment:
      MYSQL_DATABASE: insite
      MYSQL_USER: thirty
      MYSQL_PASSWORD: behappy1234
      MYSQL_ROOT_PASSWORD: 1234
    volumes:
      - "./mysql/conf.d:/etc/mysql/conf.d"
      - "./mysql/data:/var/lib/mysql"
    container_name: mysql-insite

  redis:
    image: redis:latest
    ports:
      - "6381:6379"
    environment:
      - REDIS_PASSWORD=behappy1234
    container_name: redis-insite